export const cards = [
  {
    id: 1,
    title: "Cleaning",
    img: "https://img.freepik.com/premium-photo/portrait-woman-cleaner-uniform-office-home-cleaning-services_752325-14446.jpg",
  },
  {
    id: 2,
    title: "Childcare",
    img: "https://procaresoftware.com/wp-content/uploads/2020/04/blog-sub_build-better-daycare-1-9855753.jpg",
  },
  {
    id: 3,
    title: "PetCare",
    img: "https://www.offermaids.com/blog/wp-content/uploads/2022/09/o3.jpg",
  },
  {
    id: 4,
    title: "Plumbing",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQys8eTaJMDr4tEeioluEBgkWDyzWF0n9G1ddLBRcJ2tfXm2_dE5nOpSufUWKbC2806AZU&usqp=CAU",
  },
  {
    id: 5,
    title: "Electrical",
    img: "https://d17x34b9fcvxk7.cloudfront.net/static/marketing/images/hero-backgrounds/electrician.jpg",
  },
  {
    id: 6,
    title: "Gardening",
    img: "https://cdn.mos.cms.futurecdn.net/JvbeUXjvJAdLnMUAM9UtgQ-1200-80.jpg",
  },
  {
    id: 7,
    title: "Painting",
    img: "https://www.thespruce.com/thmb/PK01FU-mg7rXlC2B_1-Mm0qNs8s=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Stocksy_txpdc39b9790by000_Medium_867684-5a958e10119fa80036fb82b6.jpg",
  },
  {
    id: 8,
    title: "Carpentry",
    img: "https://volpatolasm.com/wp-content/uploads/2022/09/laboratorio-falegnameria.jpg",
  },
  {
    id: 9,
    title: "Emergency",
    img: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/24-7-emergency-services-design-template-cba06a244b3e2495fa32ba302315de52_screen.jpg?ts=1649883924",
  },
];

export const cleaning = [
  {
    id: "1",
    userId: "67900302bd80617a1cec36bb",
    title: "Home Deep Cleaning Service",
    desc: "Professional deep cleaning services for your home to keep it spotless.",
    totalStars: 5,
    starNumber: 1,
    cat: "cleaning",
    price: 1200,
    cover: "/pictures-ss/cleaning/cl1.png",
    shortTitle: "Deep Cleaning",
    shortDesc: "Comprehensive cleaning services for your home.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Floor Cleaning", "Window Cleaning", "Bathroom Scrubbing"],
  },
  {
    id: "2",
    userId: "67900302bd80617a1cec36bb",
    title: "Office Cleaning Services",
    desc: "Affordable and professional office cleaning services for a hygienic workspace.",
    totalStars: 4,
    starNumber: 1,
    cat: "cleaning",
    price: 1500,
    cover: "/pictures-ss/cleaning/cl2.jpeg",
    shortTitle: "Office Cleaning",
    shortDesc: "Keep your office neat and tidy.",
    deliveryTime: 3,
    revisionNumber: 2,
    features: ["Workstation Dusting", "Vacuuming", "Trash Disposal"],
  },
  {
    id: "3",
    userId: "67900302bd80617a1cec36bb",
    title: "Kitchen Cleaning Experts",
    desc: "Thorough cleaning of your kitchen, including grease removal and sanitization.",
    totalStars: 5,
    starNumber: 2,
    cat: "cleaning",
    price: 900,
    cover: "/pictures-ss/cleaning/cl3.png",
    shortTitle: "Kitchen Cleaning",
    shortDesc: "Grease-free, sparkling kitchens guaranteed.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Grease Removal", "Cabinet Wiping", "Appliance Cleaning"],
  },
  {
    id: "4",
    userId: "67900302bd80617a1cec36bb",
    title: "Carpet Cleaning Service",
    desc: "Get your carpets cleaned and deodorized by experts.",
    totalStars: 3,
    starNumber: 1,
    cat: "cleaning",
    price: 1000,
    cover: "/pictures-ss/cleaning/cl4.jpeg",
    shortTitle: "Carpet Cleaning",
    shortDesc: "Fresh and clean carpets in no time.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Spot Removal", "Deodorization", "Stain Protection"],
  },
  {
    id: "5",
    userId: "67900302bd80617a1cec36bb",
    title: "Bathroom Cleaning Service",
    desc: "Professional bathroom cleaning for a spotless and sanitized space.",
    totalStars: 4,
    starNumber: 2,
    cat: "cleaning",
    price: 800,
    cover: "/pictures-ss/cleaning/cl5.jpg",
    shortTitle: "Bathroom Cleaning",
    shortDesc: "Thoroughly cleaned and sanitized bathrooms.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Toilet Scrubbing", "Tile Cleaning", "Mirror Polishing"],
  },
  {
    id: "6",
    userId: "67900302bd80617a1cec36bb",
    title: "Window Cleaning Experts",
    desc: "Crystal clear windows for homes and offices.",
    totalStars: 5,
    starNumber: 3,
    cat: "cleaning",
    price: 500,
    cover: "/pictures-ss/cleaning/cl6.jpeg",
    shortTitle: "Window Cleaning",
    shortDesc: "Sparkling windows every time.",
    deliveryTime: 1,
    revisionNumber: 2,
    features: ["Interior Windows", "Exterior Windows", "Frame Cleaning"],
  },
  {
    id: "7",
    userId: "67900302bd80617a1cec36bb",
    title: "Move-Out Cleaning Service",
    desc: "Make your old home ready for new occupants with a detailed cleaning.",
    totalStars: 3,
    starNumber: 1,
    cat: "cleaning",
    price: 2000,
    cover: "/pictures-ss/cleaning/cl7.jpeg",
    shortTitle: "Move-Out Cleaning",
    shortDesc: "Complete move-out cleaning services.",
    deliveryTime: 4,
    revisionNumber: 2,
    features: ["Kitchen Cleaning", "Floor Polishing", "Trash Removal"],
  },
  {
    id: "8",
    userId: "67900302bd80617a1cec36bb",
    title: "Sofa and Upholstery Cleaning",
    desc: "Keep your furniture fresh and stain-free with expert cleaning.",
    totalStars: 4,
    starNumber: 2,
    cat: "cleaning",
    price: 1100,
    cover: "/pictures-ss/cleaning/cl8.jpg",
    shortTitle: "Sofa Cleaning",
    shortDesc: "Fresh furniture guaranteed.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Spot Removal", "Fabric Safe Cleaning", "Deodorization"],
  },
  {
    id: "9",
    userId: "67900302bd80617a1cec36bb",
    title: "Eco-Friendly Cleaning Services",
    desc: "Cleaning services using eco-friendly and safe materials.",
    totalStars: 5,
    starNumber: 2,
    cat: "cleaning",
    price: 1300,
    cover: "/pictures-ss/cleaning/cl9.jpeg",
    shortTitle: "Eco Cleaning",
    shortDesc: "Eco-friendly cleaning solutions.",
    deliveryTime: 3,
    revisionNumber: 1,
    features: ["Eco-Friendly Products", "Safe for Kids", "Non-Toxic"],
  },
];

export const childcare = [
  {
    id: "10",
    userId: "67900302bd80617a1cec36bb",
    title: "Babysitting Service",
    desc: "Professional babysitting for children aged 2-12, ensuring safety and fun.",
    totalStars: 5,
    starNumber: 1,
    cat: "childcare",
    price: 500,
    cover: "/pictures-ss/childcare/cc1.jpeg",
    shortTitle: "Babysitting",
    shortDesc: "Reliable babysitting services.",
    deliveryTime: 1,
    revisionNumber: 2,
    features: ["Storytelling", "Meal Prep", "Games"],
  },
  {
    id: "11",
    userId: "67900302bd80617a1cec36bb",
    title: "Special Needs Care",
    desc: "Experienced caregivers for children with special needs.",
    totalStars: 4,
    starNumber: 2,
    cat: "childcare",
    price: 1200,
    cover: "/pictures-ss/childcare/cc2.jpeg",
    shortTitle: "Special Needs Care",
    shortDesc: "Caring for special children with love.",
    deliveryTime: 2,
    revisionNumber: 2,
    features: ["Customized Care", "Therapy Assistance", "Gentle Approach"],
  },
  {
    id: "12",
    userId: "67900302bd80617a1cec36bb",
    title: "After-School Care",
    desc: "Helping your child with homework and activities after school hours.",
    totalStars: 5,
    starNumber: 1,
    cat: "childcare",
    price: 700,
    cover: "/pictures-ss/childcare/cc3.jpeg",
    shortTitle: "After-School Care",
    shortDesc: "Homework help and care.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Homework Help", "Snacks Provided", "Activity Supervision"],
  },
  {
    id: "13",
    userId: "67900302bd80617a1cec36bb",
    title: "Infant Care Service",
    desc: "Gentle and reliable care for your little ones under 2 years.",
    totalStars: 4,
    starNumber: 2,
    cat: "childcare",
    price: 1500,
    cover: "/pictures-ss/childcare/cc4.jpg",
    shortTitle: "Infant Care",
    shortDesc: "Loving care for your baby.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Feeding", "Diaper Changing", "Playtime"],
  },
  {
    id: "14",
    userId: "67900302bd80617a1cec36bb",
    title: "Overnight Babysitting",
    desc: "Overnight care for your children, so you can relax and unwind.",
    totalStars: 5,
    starNumber: 1,
    cat: "childcare",
    price: 2000,
    cover: "/pictures-ss/childcare/cc5.jpg",
    shortTitle: "Overnight Care",
    shortDesc: "Trusted overnight babysitting.",
    deliveryTime: 3,
    revisionNumber: 1,
    features: ["Overnight Stay", "Storytime", "Breakfast Preparation"],
  },
  {
    id: "15",
    userId: "67900302bd80617a1cec36bb",
    title: "Weekend Childcare",
    desc: "Fun and reliable childcare for weekends and holidays.",
    totalStars: 4,
    starNumber: 3,
    cat: "childcare",
    price: 800,
    cover: "/pictures-ss/childcare/cc6.jpeg",
    shortTitle: "Weekend Care",
    shortDesc: "Weekend babysitting service.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Games", "Meal Prep", "Safe Activities"],
  },
  {
    id: "16",
    userId: "67900302bd80617a1cec36bb",
    title: "Nanny Services",
    desc: "Full-time nanny services for your growing family.",
    totalStars: 5,
    starNumber: 2,
    cat: "childcare",
    price: 2500,
    cover: "/pictures-ss/childcare/cc7.jpeg",
    shortTitle: "Nanny Services",
    shortDesc: "Experienced full-time nanny.",
    deliveryTime: 4,
    revisionNumber: 2,
    features: ["Meal Prep", "Daily Activities", "Safety First"],
  },
  {
    id: "17",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Babysitting",
    desc: "Last-minute babysitting for your urgent needs.",
    totalStars: 5,
    starNumber: 1,
    cat: "childcare",
    price: 1000,
    cover: "/pictures-ss/childcare/cc8.jpeg",
    shortTitle: "Emergency Babysitting",
    shortDesc: "On-call babysitting.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Quick Arrival", "Full Care", "Flexible Hours"],
  },
  {
    id: "18",
    userId: "67900302bd80617a1cec36bb",
    title: "Tutor + Childcare Combo",
    desc: "Get childcare and tutoring services in one package.",
    totalStars: 5,
    starNumber: 3,
    cat: "childcare",
    price: 1800,
    cover: "/pictures-ss/childcare/cc9.jpg",
    shortTitle: "Tutor + Care",
    shortDesc: "Learning and care together.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Homework Help", "Caregiving", "Flexible Timings"],
  },
];

export const petcare = [
  {
    id: "19",
    userId: "67900302bd80617a1cec36bb",
    title: "Dog Walking Service",
    desc: "Reliable and fun dog walking services for your furry friends.",
    totalStars: 5,
    starNumber: 3,
    cat: "petcare",
    price: 300,
    cover: "/pictures-ss/petcare/pc1.jpg",
    shortTitle: "Dog Walking",
    shortDesc: "Fun and safe walks for dogs.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Leash Walking", "Exercise", "Feeding (if required)"],
  },
  {
    id: "20",
    userId: "67900302bd80617a1cec36bb",
    title: "Cat Sitting Service",
    desc: "Loving care for your cats while you're away.",
    totalStars: 4,
    starNumber: 2,
    cat: "petcare",
    price: 400,
    cover: "/pictures-ss/petcare/pc2.jpeg",
    shortTitle: "Cat Sitting",
    shortDesc: "Reliable cat sitting services.",
    deliveryTime: 1,
    revisionNumber: 2,
    features: ["Feeding", "Playtime", "Litter Box Cleaning"],
  },
  {
    id: "21",
    userId: "67900302bd80617a1cec36bb",
    title: "Pet Grooming Services",
    desc: "Professional grooming services to keep your pets clean and happy.",
    totalStars: 5,
    starNumber: 2,
    cat: "petcare",
    price: 800,
    cover: "/pictures-ss/petcare/pc3.jpg",
    shortTitle: "Pet Grooming",
    shortDesc: "Pamper your pets with grooming.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Bathing", "Hair Trimming", "Nail Clipping"],
  },
  {
    id: "22",
    userId: "67900302bd80617a1cec36bb",
    title: "Pet Boarding Services",
    desc: "Safe and comfortable boarding facilities for your pets.",
    totalStars: 4,
    starNumber: 2,
    cat: "petcare",
    price: 1200,
    cover: "/pictures-ss/petcare/pc4.jpeg",
    shortTitle: "Pet Boarding",
    shortDesc: "Comfortable boarding for pets.",
    deliveryTime: 3,
    revisionNumber: 2,
    features: ["Daily Exercise", "Feeding", "24/7 Supervision"],
  },
  {
    id: "23",
    userId: "67900302bd80617a1cec36bb",
    title: "Pet Training Services",
    desc: "Behavioral training to help your pets become better companions.",
    totalStars: 5,
    starNumber: 3,
    cat: "petcare",
    price: 1500,
    cover: "/pictures-ss/petcare/pc5.png",
    shortTitle: "Pet Training",
    shortDesc: "Professional training for your pets.",
    deliveryTime: 4,
    revisionNumber: 2,
    features: ["Obedience Training", "Socialization", "Behavior Correction"],
  },
  {
    id: "24",
    userId: "67900302bd80617a1cec36bb",
    title: "Exotic Pet Care",
    desc: "Specialized care for exotic pets like reptiles, birds, and rodents.",
    totalStars: 4,
    starNumber: 2,
    cat: "petcare",
    price: 1800,
    cover: "/pictures-ss/petcare/pc6.jpeg",
    shortTitle: "Exotic Care",
    shortDesc: "Care for exotic pets.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Custom Feeding", "Habitat Cleaning", "Special Handling"],
  },
  {
    id: "25",
    userId: "67900302bd80617a1cec36bb",
    title: "Veterinary Assistance at Home",
    desc: "Get veterinary consultations and treatments at your doorstep.",
    totalStars: 5,
    starNumber: 2,
    cat: "petcare",
    price: 2000,
    cover: "/pictures-ss/petcare/pc7.jpeg",
    shortTitle: "Vet Assistance",
    shortDesc: "Home-based veterinary care.",
    deliveryTime: 1,
    revisionNumber: 2,
    features: ["Checkups", "Minor Treatments", "Vaccinations"],
  },
  {
    id: "26",
    userId: "67900302bd80617a1cec36bb",
    title: "Pet Adoption Assistance",
    desc: "Helping you find the perfect furry companion.",
    totalStars: 4,
    starNumber: 1,
    cat: "petcare",
    price: 600,
    cover: "/pictures-ss/petcare/pc8.jpeg",
    shortTitle: "Adoption Help",
    shortDesc: "Adopt a pet with ease.",
    deliveryTime: 3,
    revisionNumber: 1,
    features: ["Pet Matching", "Adoption Paperwork", "Guidance"],
  },
  {
    id: "27",
    userId: "67900302bd80617a1cec36bb",
    title: "Pet Photography",
    desc: "Capture memorable moments with your pets.",
    totalStars: 5,
    starNumber: 3,
    cat: "petcare",
    price: 1000,
    cover: "/pictures-ss/petcare/pc9.jpeg",
    shortTitle: "Pet Photography",
    shortDesc: "Beautiful pet portraits.",
    deliveryTime: 2,
    revisionNumber: 2,
    features: ["Photo Sessions", "High-Quality Prints", "Custom Backgrounds"],
  },
];

export const plumbing = [
  {
    id: "28",
    userId: "67900302bd80617a1cec36bb",
    title: "Fix Leaking Taps",
    desc: "Repair dripping taps and save water efficiently.",
    totalStars: 5,
    starNumber: 1,
    cat: "plumbing",
    price: 300,
    cover: "/pictures-ss/plumbing/pb1.jpg",
    shortTitle: "Leaking Taps",
    shortDesc: "Quick and affordable tap repairs.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Leak Repair", "Water Pressure Adjustment", "Quick Fix"],
  },
  {
    id: "29",
    userId: "67900302bd80617a1cec36bb",
    title: "Blocked Drain Services",
    desc: "Unclog drains quickly and effectively.",
    totalStars: 5,
    starNumber: 2,
    cat: "plumbing",
    price: 700,
    cover: "/pictures-ss/plumbing/pb2.jpg",
    shortTitle: "Drain Unclogging",
    shortDesc: "Unclogging services for all types of drains.",
    deliveryTime: 1,
    revisionNumber: 2,
    features: ["Kitchen Sink Drains", "Bathroom Drains", "Sewer Lines"],
  },
  {
    id: "30",
    userId: "67900302bd80617a1cec36bb",
    title: "Toilet Installation and Repair",
    desc: "Install or repair toilets for your home or office.",
    totalStars: 4,
    starNumber: 1,
    cat: "plumbing",
    price: 1500,
    cover: "/pictures-ss/plumbing/pb3.jpeg",
    shortTitle: "Toilet Repair",
    shortDesc: "Reliable toilet installation and repair.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Flush Mechanism", "Seat Replacement", "Leak Fixing"],
  },
  {
    id: "31",
    userId: "67900302bd80617a1cec36bb",
    title: "Water Heater Installation",
    desc: "Professional installation of water heaters for all needs.",
    totalStars: 5,
    starNumber: 3,
    cat: "plumbing",
    price: 2500,
    cover: "/pictures-ss/plumbing/pb4.jpg",
    shortTitle: "Water Heater",
    shortDesc: "Efficient water heater installation services.",
    deliveryTime: 3,
    revisionNumber: 2,
    features: [
      "Tankless Heaters",
      "Gas and Electric Heaters",
      "Thermostat Setup",
    ],
  },
  {
    id: "32",
    userId: "67900302bd80617a1cec36bb",
    title: "Pipe Leakage Detection",
    desc: "Identify and fix hidden water leaks in your pipes.",
    totalStars: 5,
    starNumber: 2,
    cat: "plumbing",
    price: 1200,
    cover: "/pictures-ss/plumbing/pb5.jpg",
    shortTitle: "Leak Detection",
    shortDesc: "Expert pipe leakage solutions.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Thermal Detection", "Repair Services", "Damage Prevention"],
  },
  {
    id: "33",
    userId: "67900302bd80617a1cec36bb",
    title: "Bathroom Fittings Installation",
    desc: "Install modern and stylish bathroom fittings.",
    totalStars: 4,
    starNumber: 1,
    cat: "plumbing",
    price: 3000,
    cover: "/pictures-ss/plumbing/pb6.jpeg",
    shortTitle: "Fittings Installation",
    shortDesc: "Upgrade your bathroom with premium fittings.",
    deliveryTime: 4,
    revisionNumber: 2,
    features: ["Showers", "Taps", "Bathtubs"],
  },
  {
    id: "34",
    userId: "67900302bd80617a1cec36bb",
    title: "Water Pump Repairs",
    desc: "Quick and effective water pump repair services.",
    totalStars: 5,
    starNumber: 1,
    cat: "plumbing",
    price: 2000,
    cover: "/pictures-ss/plumbing/pb7.jpeg",
    shortTitle: "Pump Repairs",
    shortDesc: "Keep your water pump running smoothly.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Motor Repair", "Pump Replacement", "Pipe Connections"],
  },
  {
    id: "35",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Plumbing Services",
    desc: "On-call emergency plumbing services for urgent needs.",
    totalStars: 5,
    starNumber: 1,
    cat: "plumbing",
    price: 3500,
    cover: "/pictures-ss/plumbing/pb8.jpeg",
    shortTitle: "Emergency Plumbing",
    shortDesc: "24/7 plumbing assistance.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Quick Arrival", "Complete Repairs", "Customer Support"],
  },
  {
    id: "36",
    userId: "67900302bd80617a1cec36bb",
    title: "Underground Pipe Repair",
    desc: "Fix leaks and damages in underground pipes.",
    totalStars: 4,
    starNumber: 2,
    cat: "plumbing",
    price: 4000,
    cover: "/pictures-ss/plumbing/pb9.png",
    shortTitle: "Underground Repair",
    shortDesc: "Specialized underground pipe services.",
    deliveryTime: 5,
    revisionNumber: 2,
    features: ["Trenchless Repair", "Pipe Replacement", "Leak Detection"],
  },
];

export const electrical = [
  {
    id: "37",
    userId: "67900302bd80617a1cec36bb",
    title: "Fan Installation and Repair",
    desc: "Install or repair ceiling and table fans with ease.",
    totalStars: 5,
    starNumber: 2,
    cat: "electrical",
    price: 1000,
    cover: "/pictures-ss/electrical/ec1.jpg",
    shortTitle: "Fan Installation",
    shortDesc: "Quick fan installation and repair.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Ceiling Fans", "Table Fans", "Speed Control"],
  },
  {
    id: "38",
    userId: "67900302bd80617a1cec36bb",
    title: "Wiring and Rewiring Services",
    desc: "Professional wiring and rewiring for homes and offices.",
    totalStars: 4,
    starNumber: 1,
    cat: "electrical",
    price: 2500,
    cover: "/pictures-ss/electrical/ec2.jpeg",
    shortTitle: "Wiring Services",
    shortDesc: "Safe and reliable wiring solutions.",
    deliveryTime: 3,
    revisionNumber: 1,
    features: ["Room Wiring", "Switchboard Installation", "Circuit Fixing"],
  },
  {
    id: "39",
    userId: "67900302bd80617a1cec36bb",
    title: "Power Backup Installation",
    desc: "Set up inverters or UPS for uninterrupted power supply.",
    totalStars: 5,
    starNumber: 2,
    cat: "electrical",
    price: 5000,
    cover: "/pictures-ss/electrical/ec3.jpeg",
    shortTitle: "Power Backup",
    shortDesc: "Stay powered during outages.",
    deliveryTime: 2,
    revisionNumber: 2,
    features: ["Inverter Setup", "Battery Connection", "Surge Protection"],
  },
  {
    id: "40",
    userId: "67900302bd80617a1cec36bb",
    title: "Lighting Installation",
    desc: "Install decorative and functional lights for your space.",
    totalStars: 4,
    starNumber: 2,
    cat: "electrical",
    price: 1200,
    cover: "/pictures-ss/electrical/ec4.jpeg",
    shortTitle: "Lighting Setup",
    shortDesc: "Add light to your life.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["LED Lights", "Decorative Fixtures", "Outdoor Lighting"],
  },
  {
    id: "41",
    userId: "67900302bd80617a1cec36bb",
    title: "Fuse and Circuit Breaker Repairs",
    desc: "Fix blown fuses or replace circuit breakers promptly.",
    totalStars: 5,
    starNumber: 2,
    cat: "electrical",
    price: 800,
    cover: "/pictures-ss/electrical/ec5.jpg",
    shortTitle: "Fuse Repair",
    shortDesc: "Expert fuse and breaker fixes.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: [
      "Circuit Breakers",
      "Short Circuit Fixes",
      "Overload Protection",
    ],
  },
  {
    id: "42",
    userId: "67900302bd80617a1cec36bb",
    title: "Smart Home Installation",
    desc: "Upgrade your home with smart devices and automation.",
    totalStars: 5,
    starNumber: 3,
    cat: "electrical",
    price: 8000,
    cover: "/pictures-ss/electrical/ec6.jpg",
    shortTitle: "Smart Home Setup",
    shortDesc: "Bring technology to your home.",
    deliveryTime: 4,
    revisionNumber: 2,
    features: ["Smart Lights", "CCTV Cameras", "Home Automation"],
  },
  {
    id: "43",
    userId: "67900302bd80617a1cec36bb",
    title: "AC Installation and Repair",
    desc: "Professional installation and servicing for air conditioners.",
    totalStars: 5,
    starNumber: 2,
    cat: "electrical",
    price: 3000,
    cover: "/pictures-ss/electrical/ec7.jpg",
    shortTitle: "AC Services",
    shortDesc: "Stay cool with our AC services.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Split AC", "Window AC", "Cooling Efficiency"],
  },
  {
    id: "44",
    userId: "67900302bd80617a1cec36bb",
    title: "Generator Maintenance Services",
    desc: "Ensure your generator works seamlessly during outages.",
    totalStars: 4,
    starNumber: 1,
    cat: "electrical",
    price: 4500,
    cover: "/pictures-ss/electrical/ec8.jpeg",
    shortTitle: "Generator Maintenance",
    shortDesc: "Keep your generator running.",
    deliveryTime: 3,
    revisionNumber: 1,
    features: ["Oil Change", "Battery Check", "Engine Repairs"],
  },
  {
    id: "45",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Electrical Services",
    desc: "On-call electrical services for urgent situations.",
    totalStars: 5,
    starNumber: 1,
    cat: "electrical",
    price: 3500,
    cover: "/pictures-ss/electrical/ec9.jpg",
    shortTitle: "Emergency Electrical",
    shortDesc: "24/7 electrical help.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Power Restoration", "Quick Fixes", "On-Demand Support"],
  },
];

export const gardening = [
  {
    id: "46",
    userId: "67900302bd80617a1cec36bb",
    title: "Lawn Mowing Service",
    desc: "Keep your lawn neat and tidy with expert mowing services.",
    totalStars: 5,
    starNumber: 3,
    cat: "gardening",
    price: 500,
    cover: "/pictures-ss/gr/gr1.jpeg",
    shortTitle: "Lawn Mowing",
    shortDesc: "Neat and trimmed lawns.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Precision Cutting", "Edging", "Debris Removal"],
  },
  {
    id: "47",
    userId: "67900302bd80617a1cec36bb",
    title: "Garden Maintenance",
    desc: "Full garden maintenance services to keep your garden thriving.",
    totalStars: 4,
    starNumber: 2,
    cat: "gardening",
    price: 1200,
    cover: "/pictures-ss/gr/gr2.jpg",
    shortTitle: "Garden Care",
    shortDesc: "Healthy and beautiful gardens.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Weeding", "Soil Aeration", "Pest Control"],
  },
  {
    id: "48",
    userId: "67900302bd80617a1cec36bb",
    title: "Plantation Services",
    desc: "Plant trees, shrubs, and flowers for a vibrant garden.",
    totalStars: 5,
    starNumber: 2,
    cat: "gardening",
    price: 2000,
    cover: "/pictures-ss/gr/gr3.jpg",
    shortTitle: "Plantation",
    shortDesc: "Add greenery to your garden.",
    deliveryTime: 3,
    revisionNumber: 2,
    features: ["Tree Plantation", "Seasonal Flowers", "Soil Testing"],
  },
  {
    id: "49",
    userId: "67900302bd80617a1cec36bb",
    title: "Hedge Trimming Services",
    desc: "Shape and maintain your hedges with expert trimming.",
    totalStars: 4,
    starNumber: 1,
    cat: "gardening",
    price: 800,
    cover: "/pictures-ss/gr/gr4.jpeg",
    shortTitle: "Hedge Trimming",
    shortDesc: "Beautifully trimmed hedges.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Precision Cutting", "Shaping", "Waste Disposal"],
  },
  {
    id: "50",
    userId: "67900302bd80617a1cec36bb",
    title: "Sprinkler Installation",
    desc: "Install an efficient sprinkler system for your lawn or garden.",
    totalStars: 5,
    starNumber: 2,
    cat: "gardening",
    price: 5000,
    cover: "/pictures-ss/gr/gr5.jpeg",
    shortTitle: "Sprinkler Setup",
    shortDesc: "Automated watering systems.",
    deliveryTime: 4,
    revisionNumber: 2,
    features: ["Timer Setup", "Coverage Optimization", "Leak Testing"],
  },
  {
    id: "51",
    userId: "67900302bd80617a1cec36bb",
    title: "Composting Services",
    desc: "Turn your organic waste into nutrient-rich compost for your plants.",
    totalStars: 5,
    starNumber: 3,
    cat: "gardening",
    price: 1200,
    cover: "/pictures-ss/gr/gr6.jpg",
    shortTitle: "Composting",
    shortDesc: "Eco-friendly composting solutions.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Bin Setup", "Waste Collection", "Soil Enrichment"],
  },
  {
    id: "52",
    userId: "67900302bd80617a1cec36bb",
    title: "Vertical Gardening",
    desc: "Transform your walls into lush green spaces with vertical gardens.",
    totalStars: 4,
    starNumber: 2,
    cat: "gardening",
    price: 8000,
    cover: "/pictures-ss/gr/gr7.jpg",
    shortTitle: "Wall Gardens",
    shortDesc: "Green walls for modern homes.",
    deliveryTime: 5,
    revisionNumber: 2,
    features: ["Plant Arrangement", "Wall Fixtures", "Irrigation Systems"],
  },
  {
    id: "53",
    userId: "67900302bd80617a1cec36bb",
    title: "Seasonal Flower Planting",
    desc: "Brighten up your garden with seasonal flowers.",
    totalStars: 5,
    starNumber: 1,
    cat: "gardening",
    price: 1500,
    cover: "/pictures-ss/gr/gr8.jpeg",
    shortTitle: "Flower Planting",
    shortDesc: "Add color to your garden.",
    deliveryTime: 3,
    revisionNumber: 1,
    features: ["Flower Beds", "Soil Preparation", "Seasonal Care"],
  },
  {
    id: "54",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Gardening Services",
    desc: "Quick gardening services for special events or urgent needs.",
    totalStars: 4,
    starNumber: 1,
    cat: "gardening",
    price: 4000,
    cover: "/pictures-ss/gr/gr9.jpg",
    shortTitle: "Event Gardening",
    shortDesc: "Gardens ready for your events.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Quick Setup", "Decoration", "Waste Cleanup"],
  },
];

export const painting = [
  {
    id: "55",
    userId: "67900302bd80617a1cec36bb",
    title: "Interior Wall Painting",
    desc: "Get your interiors painted with vibrant and high-quality colors.",
    totalStars: 5,
    starNumber: 3,
    cat: "painting",
    price: 5000,
    cover: "/pictures-ss/painting/pa1.jpg",
    shortTitle: "Interior Painting",
    shortDesc: "Brighten up your interiors.",
    deliveryTime: 3,
    revisionNumber: 2,
    features: ["Premium Paints", "Accent Walls", "Quick Drying"],
  },
  {
    id: "56",
    userId: "67900302bd80617a1cec36bb",
    title: "Exterior Wall Painting",
    desc: "Durable and weather-resistant paint for the exterior of your building.",
    totalStars: 5,
    starNumber: 2,
    cat: "painting",
    price: 8000,
    cover: "/pictures-ss/painting/pa2.jpg",
    shortTitle: "Exterior Painting",
    shortDesc: "Weatherproof painting solutions.",
    deliveryTime: 5,
    revisionNumber: 2,
    features: ["Waterproof Paints", "Weather Resistance", "Fungus Protection"],
  },
  {
    id: "57",
    userId: "67900302bd80617a1cec36bb",
    title: "Wood Polishing Services",
    desc: "Polish your wooden furniture and floors for a shiny and new look.",
    totalStars: 4,
    starNumber: 1,
    cat: "painting",
    price: 3000,
    cover: "/pictures-ss/painting/pa3.jpg",
    shortTitle: "Wood Polishing",
    shortDesc: "Restore shine to wood.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Furniture Polishing", "Floor Polishing", "Scratch Removal"],
  },
  {
    id: "58",
    userId: "67900302bd80617a1cec36bb",
    title: "Textured Wall Painting",
    desc: "Add a premium textured finish to your walls for a unique look.",
    totalStars: 5,
    starNumber: 1,
    cat: "painting",
    price: 6000,
    cover: "/pictures-ss/painting/pa4.jpeg",
    shortTitle: "Textured Painting",
    shortDesc: "Walls with a designer touch.",
    deliveryTime: 4,
    revisionNumber: 2,
    features: ["Custom Textures", "Designer Finishes", "Long-Lasting"],
  },
  {
    id: "59",
    userId: "67900302bd80617a1cec36bb",
    title: "Metal Painting Services",
    desc: "Protect your metal surfaces with high-quality painting services.",
    totalStars: 5,
    starNumber: 1,
    cat: "painting",
    price: 2000,
    cover: "/pictures-ss/painting/pa5.jpeg",
    shortTitle: "Metal Painting",
    shortDesc: "Durable metal protection.",
    deliveryTime: 1,
    revisionNumber: 1,
    features: ["Rust Protection", "Glossy Finish", "Weather Resistant"],
  },
  {
    id: "60",
    userId: "67900302bd80617a1cec36bb",
    title: "Ceiling Painting",
    desc: "Brighten up your ceilings with professional painting services.",
    totalStars: 4,
    starNumber: 1,
    cat: "painting",
    price: 4000,
    cover: "/pictures-ss/painting/pa6.jpg",
    shortTitle: "Ceiling Painting",
    shortDesc: "Perfectly painted ceilings.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Anti-Stain Paint", "Smooth Finish", "Customized Colors"],
  },
  {
    id: "61",
    userId: "67900302bd80617a1cec36bb",
    title: "Furniture Painting",
    desc: "Revive old furniture with a fresh coat of paint.",
    totalStars: 5,
    starNumber: 2,
    cat: "painting",
    price: 2500,
    cover: "/pictures-ss/painting/pa7.jpg",
    shortTitle: "Furniture Paint",
    shortDesc: "Renew your furniture.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: [
      "Wooden Furniture",
      "Glossy and Matte Options",
      "Scratch Resistant",
    ],
  },
  {
    id: "62",
    userId: "67900302bd80617a1cec36bb",
    title: "Graffiti Art Services",
    desc: "Get professional graffiti art for walls, events, or businesses.",
    totalStars: 5,
    starNumber: 2,
    cat: "painting",
    price: 8000,
    cover: "/pictures-ss/painting/pa8.jpeg",
    shortTitle: "Graffiti Art",
    shortDesc: "Add an artistic touch.",
    deliveryTime: 4,
    revisionNumber: 2,
    features: ["Custom Designs", "Vibrant Colors", "Outdoor Safe"],
  },
  {
    id: "63",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Painting Services",
    desc: "Quick painting services for events or urgent needs.",
    totalStars: 4,
    starNumber: 1,
    cat: "painting",
    price: 10000,
    cover: "/pictures-ss/painting/pa9.jpeg",
    shortTitle: "Quick Painting",
    shortDesc: "Fast and efficient painting.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Event Ready", "Quick Dry Paint", "Professional Team"],
  },
];

export const carpentry = [
  {
    id: "64",
    userId: "67900302bd80617a1cec36bb",
    title: "Custom Furniture Making",
    desc: "Design and build custom furniture to match your style.",
    totalStars: 5,
    starNumber: 3,
    cat: "carpentry",
    price: 12000,
    cover: "/pictures-ss/carpentry/ca1.jpeg",
    shortTitle: "Custom Furniture",
    shortDesc: "Unique furniture designs.",
    deliveryTime: 10,
    revisionNumber: 3,
    features: ["Custom Designs", "Premium Materials", "Durable Build"],
  },
  {
    id: "65",
    userId: "67900302bd80617a1cec36bb",
    title: "Door and Window Repairs",
    desc: "Repair damaged doors and windows for smooth operation.",
    totalStars: 4,
    starNumber: 1,
    cat: "carpentry",
    price: 2000,
    cover: "/pictures-ss/carpentry/ca2.jpeg",
    shortTitle: "Door Repairs",
    shortDesc: "Fix doors and windows.",
    deliveryTime: 2,
    revisionNumber: 1,
    features: ["Hinges Replacement", "Alignment Fixes", "Frame Repairs"],
  },
  {
    id: "66",
    userId: "67900302bd80617a1cec36bb",
    title: "Wooden Flooring Installation",
    desc: "Install durable and stylish wooden flooring for your space.",
    totalStars: 5,
    starNumber: 2,
    cat: "carpentry",
    price: 15000,
    cover: "/pictures-ss/carpentry/ca3.jpeg",
    shortTitle: "Wood Flooring",
    shortDesc: "Elegant wooden flooring.",
    deliveryTime: 7,
    revisionNumber: 2,
    features: ["Custom Patterns", "Polishing", "Scratch Resistant"],
  },
  {
    id: "67",
    userId: "67900302bd80617a1cec36bb",
    title: "Wooden Fence Installation",
    desc: "Build durable wooden fences for privacy and aesthetics.",
    totalStars: 5,
    starNumber: 3,
    cat: "carpentry",
    price: 10000,
    cover: "/pictures-ss/carpentry/ca4.jpeg",
    shortTitle: "Wooden Fences",
    shortDesc: "Secure your property with a wooden fence.",
    deliveryTime: 7,
    revisionNumber: 2,
    features: ["Privacy Fences", "Custom Heights", "Painted Finishes"],
  },
  {
    id: "68",
    userId: "67900302bd80617a1cec36bb",
    title: "Bookshelf and Cabinet Making",
    desc: "Custom-made bookshelves and cabinets to organize your space.",
    totalStars: 5,
    starNumber: 2,
    cat: "carpentry",
    price: 8000,
    cover: "/pictures-ss/carpentry/ca5.jpeg",
    shortTitle: "Bookshelves & Cabinets",
    shortDesc: "Organize your home with custom furniture.",
    deliveryTime: 5,
    revisionNumber: 2,
    features: ["Wooden Shelves", "Custom Designs", "Durable Materials"],
  },
  {
    id: "69",
    userId: "67900302bd80617a1cec36bb",
    title: "Kitchen Cabinet Installation",
    desc: "Install stylish and functional kitchen cabinets tailored to your needs.",
    totalStars: 4,
    starNumber: 3,
    cat: "carpentry",
    price: 12000,
    cover: "/pictures-ss/carpentry/ca6.jpg",
    shortTitle: "Kitchen Cabinets",
    shortDesc: "Maximize kitchen space with custom cabinets.",
    deliveryTime: 7,
    revisionNumber: 3,
    features: ["Drawer Systems", "Shelf Organization", "Custom Fit"],
  },
  {
    id: "70",
    userId: "67900302bd80617a1cec36bb",
    title: "Outdoor Deck Construction",
    desc: "Build a beautiful outdoor deck to enjoy your garden or backyard.",
    totalStars: 5,
    starNumber: 3,
    cat: "carpentry",
    price: 20000,
    cover: "/pictures-ss/carpentry/ca8.jpeg",
    shortTitle: "Outdoor Decks",
    shortDesc: "Relax in style with a custom deck.",
    deliveryTime: 10,
    revisionNumber: 3,
    features: ["Wooden Decks", "Patio Furniture", "Deck Lighting"],
  },
  {
    id: "71",
    userId: "67900302bd80617a1cec36bb",
    title: "Custom Wooden Doors",
    desc: "Design and install unique wooden doors for your house or office.",
    totalStars: 4,
    starNumber: 2,
    cat: "carpentry",
    price: 5000,
    cover: "/pictures-ss/carpentry/ca9.jpeg",
    shortTitle: "Wooden Doors",
    shortDesc: "Custom-designed wooden doors.",
    deliveryTime: 6,
    revisionNumber: 2,
    features: ["Solid Wood", "Custom Handles", "Precision Fit"],
  },
];

export const emergency = [
  {
    id: "72",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Plumber on Call",
    desc: "On-demand plumbing services for urgent repairs and leaks.",
    totalStars: 5,
    starNumber: 1,
    cat: "emergency",
    price: 2500,
    cover: "/pictures-ss/emergency/em1.jpg",
    shortTitle: "Emergency Plumbing",
    shortDesc: "24/7 emergency plumbing services.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Leak Repairs", "Pipe Fixing", "Clog Removal"],
  },
  {
    id: "73",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Electrician Service",
    desc: "On-demand electrical services for urgent repairs and installations.",
    totalStars: 5,
    starNumber: 1,
    cat: "emergency",
    price: 3000,
    cover: "/pictures-ss/emergency/em2.png",
    shortTitle: "Emergency Electrician",
    shortDesc: "Immediate electrical repairs and assistance.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Circuit Fixing", "Power Outage", "Short Circuit Repairs"],
  },
  {
    id: "74",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Locksmith Service",
    desc: "Locked out of your house or car? Get professional locksmith services.",
    totalStars: 5,
    starNumber: 2,
    cat: "emergency",
    price: 2000,
    cover: "/pictures-ss/emergency/em3.jpg",
    shortTitle: "Emergency Locksmith",
    shortDesc: "Lock and key services when you need them the most.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Car Lockouts", "Door Unlocking", "Key Replacement"],
  },
  {
    id: "75",
    userId: "67900302bd80617a1cec36bb",
    title: "Emergency Pest Control",
    desc: "Immediate pest control services to deal with infestations.",
    totalStars: 5,
    starNumber: 1,
    cat: "emergency",
    price: 3500,
    cover: "/pictures-ss/emergency/em4.png",
    shortTitle: "Emergency Pest Control",
    shortDesc: "Get rid of pests quickly and effectively.",
    deliveryTime: 1,
    revisionNumber: 0,
    features: ["Rodent Control", "Cockroach Treatment", "Bedbug Removal"],
  },
];
